name: Comment on new issues

on: 
  issues: 
    types:
      - opened
  workflow_dispatch:

jobs: 
  comment-with-action:
    permissions: write-all
    runs-on: ubuntu-latest
    steps: 
      - name: Create comment on opened issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: >
            Thank you for bringing up the 
            issue. We will look into it as 
            soon as possible.


  
